### ISSUE TITLE
MacOS Update is missing for 1.13.0

### ISSUE THREAD

**Issue by Berovowilare** [ezra-bible-app/ezra-bible-app#1015]
Hallo Tobias

Das Update für MacOS 1.13.0 fehlt in der Liste. 

Grüsse

**Comment by tobias-klein** [comment]
Yes, this will hopefully come in the evening (CET) today. See my comment on the release discussion.

**Comment by Berovowilare** [comment]
Danke, hab' ich gar nicht gesehen. 

Grüsse

**Comment by tobias-klein** [comment]
The dmg file is available now:

https://github.com/ezra-bible-app/ezra-bible-app/releases/download/1.13.0/ezra-bible-app_mac_1.13.0_x64.dmg

**Comment by Berovowilare** [comment]
Danke dir.

Grüsse
