### ISSUE TITLE
Ubuntu 22.04 unity: Launcher not displayed in dashboard

### ISSUE THREAD

**Issue by LAfricain** [ezra-bible-app/ezra-bible-app#1017]
If I change windows, I have to reopen Ezra. I'm running ubuntu 22.04 unity.

**Comment by tobias-klein** [comment]
@LAfricain Thanks for reporting this. I do not understand exactly what the issue is, though. Would you mind attaching a screenshot to illustrate the issue?

**Comment by LAfricain** [comment]
when yo open an app. The launcher appears in the taskbar/dashboard. On Unity it appears to the left dashboard. But when I open Ezra, I can't the app in the taskbar. And when I reduce it, it "disappears".
A screenshot will not be useful because we have nothing to show :)

**Comment by tobias-klein** [comment]
Mmmm. Ok. I will try to reproduce this in a Ubuntu 22.04 VM.

**Comment by LAfricain** [comment]
It's solved in the last version 1.13.

**Comment by LAfricain** [comment]
Great job your new version...

**Comment by tobias-klein** [comment]
> Great job your new version...

Thanks! I am glad you like it! :)
