### ISSUE TITLE
Startmenu Windows 11

### ISSUE THREAD

**Issue by oehajo** [ezra-bible-app/ezra-bible-app#1027]
Dear Developers,

I installed Ezra-Bible-App

But i can´t find it in the Windows Startmenu. 
What is the name of the executable file, and where can i find it?.

**Comment by tobias-klein** [comment]
Normally, the entry in the start menu should be called Ezra Bible App.

Which Windows version are you using? 
Which version of Ezra Bible App are you using?

**Comment by oehajo** [comment]
Dear Tobias,

i'm using Windows 11. There was no entry in Startmenu created.

Perhaps i'll better wait for new version, cause after 3 or 4 starts every downloaded bible or other book suddenly seeemed lost.

By the way, Your name sounds german. Do You speak German?

Have a nice day and a good start to the new Werk.

Hansjörg Oehme

2. Corintians 13, 13

08.06.2024 16:20:40 Tobias Klein ***@***.***>:

**Comment by tobias-klein** [comment]
Hallo Hansjörg,

wie der von dir beschriebene Datenverlust zu Stande kommt, kann ich leider nicht nachvollziehen. Ich habe hier kein Windows 11. Ich muss mal nach einer passenden virtuellen Maschine schauen bei nächster Gelegenheit.
Der Speicherort ist im Standardverzeichnis des bei der Installation verwendeten Benutzers, ggf mal unter "App Data" (oder ähnlich) schauen, das ist allerdings ein standardmäßig ausgeblendetes Verzeichnis. 

Viele Grüße
Tobias

**Comment by PlaidDroid** [comment]
I can confirm that the app icon is visible in the Start menu of Windows 11 in v1.14.0.

Windows version details:
```
Edition: Windows 11 Home Single Language  
Version: 23H2  
Installed on: ‎28-‎09-‎2022  
OS build: 22631.3880  
Experience: Windows Feature Experience Pack 1000.22700.1020.0  
```

**Comment by tobias-klein** [comment]
@PlaidDroid Thanks for the feedback, that is helpful. I still do not have a Windows 11 test machine.

**Comment by oehajo** [comment]
Hello Sir,

yes thanks, now it is. But it surely wasn't, when i installed the app in the Version before.

I appreciate the Work, done in the new version of ezra-bible-app.

I'm not trained in GitHub. Ist there any posibility to mark my question as "solved"?

Have a nice weekend.

Hansjörg Oehme

20.07.2024 10:00:09 PlaidDroid ***@***.***>:
