### ISSUE TITLE
Search results for Strongs H* numbers lack highlighting

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1084]
This affects both the mobile and desktop. When searching for a G* Strongs number, the results are highlighted (the relevant English represented by the searched for Strongs #) but if you trying searching for a H* Strongs number, the results lack highlighting.

**Comment by tobias-klein** [comment]
I transferred the first issue from the Cordova repo to #1085. Now this one is duplicate and therefore I am closing it.
