### ISSUE TITLE
Search results for Strongs Hebrew #'s lack highlight

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1085]
When I search for a G* Strongs number, in the results the word(s) represented in English by the Strongs # is highlighted in yellow. However, when I search for a H* Strongs number, the results lack the highlighting.

Android version 12 (June 5, 2024 security update, June 1, 2024 Google play system update)

Ezra Application version 1.14.0 (Git commit 73e1e8a5)
Sword version 1.9.0.60b6e1 (SVN Rev. 3844)
Chromium version 126.0.6478.186

**Comment by tobias-klein** [comment]
@toazd This seems a specific issue connected to the way how Hebrew Strongs numbers are appearing in the markup of the KJV (and potentially other translations, too).

In the KJV module, the Hebrew Strong's numbers in the text are prefixed by a 0. E.g. in the markup of the KJV, the Strong's number H776 appears as H**0**776. That is the root-cause of the issue.

If you perform the same search in a translation that does not have the 0 prefixes, this issue does not occur. E.g. when you try with the NASB, the highlighting should work.

I will try to see whether I can implement a work-around to deal with that 0 prefix. I have already noticed this before and have some work-around for other usecases, but I still need to analyze a bit.

**Comment by tobias-klein** [comment]
@toazd I just found an easy way to fix this. See 7533175.
As mentioned this fix will then be released as part of 1.15.

**Comment by toazd** [comment]
Thank you for looking into this and fixing it :D
