### ISSUE TITLE
Translations with leading zeros in Strong's #s (eg. H07225) cause the function "Find all occurances" to always return zero results.

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1086]
Title says it all. Same translation and same versions as the last issue that I had opened.

"King James Version (1769) with Strongs Numbers and Morphology and Catchwords [KJV]"
Version: 3.1 Size 4133 KB
Repository: Crosswire

**Comment by tobias-klein** [comment]
This is also fixed by the bugfix I did for #1085, because it has the same root cause. Therefore I'm closing this issue.

**Comment by toazd** [comment]
Ok, thank you!
