### ISSUE TITLE
Option to show Strong's #'s inline with text and/or search results

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1087]
eg.

1, ¶ In the beginning<sup>H7225</sup> God<sup>H430</sup> created<sup>H1254</sup> <sup>H853</sup> <sup>H8804</sup> the heaven<sup>H8064</sup> and<sup>H853</sup> the earth<sup>H776</sup> .

**Comment by tobias-klein** [comment]
Thanks for this suggestion @toazd. For me to understand better - what exactly is the rationale for this feature?

**Comment by toazd** [comment]
This particular feature has been a boon to my word studies of late. I'm not entirely sure all the benefits it may or may not lend. Normally, I would use bibleanalyzer for those kinds of studies but that application does not have a mobile/android version so it's limited to desktop only (I don't have a laptop). If Ezra had this feature I could do my word studies almost anywhere because it runs well on Android.

It may be easier to show you with an example:

**Genesis 6:14**
> Make thee an ark of gopher wood; rooms shalt thou make in the ark, and shalt pitch it within and without with pitch.

_Seems_ pretty straight forward right? The ark needed to be waterproofed because it needed to float on water reliably for a season.

Let's take a closer look with the Strongs #'s showing:

**Genesis 6:14** 
> Make<sup>H6213</sup> thee an ark<sup>H8392</sup> of gopher<sup>H1613</sup> wood<sup>H6086</sup>; rooms<sup>H7064</sup> shalt thou make<sup>H6213</sup> in<sup>H854</sup> the ark<sup>H8392</sup>, and shalt pitch<sup>H3722</sup> it within<sup>H1004</sup> and without<sup>H2351</sup> with pitch<sup>H3724</sup>.

Notice how the first and the second "pitch" are not the same Strong's #? There is very significant symbolism behind this _seemingly_ mundane task that Noah was charged with.

**Comment by tobias-klein** [comment]
@toazd Thanks for the explanation. I can see where you are coming from and how this could be useful for some Bible students. I will have a look regarding the needed efforts. It could be as easy as switching a certain CSS class depending on an option and therefore showing/hiding the Strong's numbers that way.

**Comment by toazd** [comment]
Thank you @tobias-klein. I don't know enough CSS or Javascript or I would try to help. If it becomes too cumbersome to implement don't worry about it. Ezra is already the only good app that I can do word studies with on mobile. None of the others that I have tried have Strong's #'s and definitions so easily integrated. So it will be my go-to for mobile study when I don't have access to my laptop for the foreseeable future.

**Comment by tobias-klein** [comment]
@toazd
I just played a bit with the existing DictionaryController code and managed to render the strongs inline based on adding a few lines of code and some CSS.

<img width="689" alt="image" src="https://github.com/user-attachments/assets/59b667af-7d7f-4b6d-bb98-25740caf01c6">

Now I still need to add a new option and make this kind of rendering optional.

**Comment by toazd** [comment]
That was quick! Looks nice!

Is it possible to make the Strong's # and the TVM # different colors from each other? Or have just one (the TVM) be a different color other than black?

**Comment by tobias-klein** [comment]
> That was quick! Looks nice!
> 
> Is it possible to make the Strong's # and the TVM # different colors from each other? Or have just one (the TVM) be a different color other than black?

We can change colors for sure. What do you mean with TVM?

**Comment by toazd** [comment]
When I wrote TVM (tense, voice, mood) I was referring to the second Strong's # if it is present. They are colored red in the following screenshot: [https://imgur.com/x0R9AOn](https://imgur.com/x0R9AOn).

**Comment by tobias-klein** [comment]
@toazd 
Which website or app is that screenshot from? Currently there is no data source in Ezra that allows rendering the TVM info. 

Regarding the colors of the strongs numbers compared to the text: And preferences?

**Comment by toazd** [comment]
The screenshot is from the app [Bibleanalyzer](https://www.bibleanalyzer.com/). Sorry, I was not aware that no data sources exist for TVM for Ezra. I also made a mistake by thinking that H834 in your screenshot was a TVM #. Still, it may be easier to read if those secondary #'s are a different color from the primary.

Instead of me choosing a color/colors it may be best to leave it the default color or what may be even better is to add options somewhere for the user to choose their own colors for different types of texts and backgrounds for both day and night mode. Not that I have any problem with the default colors but it doesn't hurt to have options for people who prefer or are used to a custom color scheme.

For example, if those options existed I would change the day mode background to a light sepia and the secondary strong's numbers to a dark red/maroon. I'm not sure why I prefer a sepia background but I would guess because it's easier on the eyes for long reading sessions (night/dark mode is almost the same).

If you choose a color other than black I would just keep in mind that some folks view colors differently (for example [dichromatic colour vision](https://www.colourblindawareness.org/colour-blindness/types-of-colour-blindness/) the person will see purple as blue).

**Comment by tobias-klein** [comment]
Thanks. I finished an implementation for this option based on #1094. Adding configurability for colors may be work for another day!

**Comment by toazd** [comment]
Thank you!

**Comment by tobias-klein** [comment]
@toazd This enhancement is now available as part of the [new release 1.15](https://github.com/ezra-bible-app/ezra-bible-app/releases/tag/1.15.0)!

**Comment by toazd** [comment]
> @toazd This enhancement is now available as part of the [new release 1.15](https://github.com/ezra-bible-app/ezra-bible-app/releases/tag/1.15.0)!

It appears to work great on desktop! Thank you that's awesome! Will that feature also be coming to the mobile version if it is not already there?

**Comment by tobias-klein** [comment]
> > @toazd This enhancement is now available as part of the [new release 1.15](https://github.com/ezra-bible-app/ezra-bible-app/releases/tag/1.15.0)!
> 
> It appears to work great on desktop! Thank you that's awesome! Will that feature also be coming to the mobile version if it is not already there?

Yes, this feature will also be available in the latest version on Android. That new version is currently still in the approval process in the PlayStore and will be published soon.
