### ISSUE TITLE
Save verse selection per tab on desktop

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1095]
This is probably an enhancement request.

In Ezra 1.14.1 on Windows desktop, when I have multiple tabs open, if I switch between the tabs it "reloads" them and for example I lose which verse I had selected. I also lose my place on a commentary if one is selected and I switch tabs :/

Is there anyway to not reload the tabs and instead keep them loaded?

**Comment by tobias-klein** [comment]
@toazd The app does remember the scroll position when switching tabs and it is restored when returning to a given tab. Can you confirm that this is working for you? What indeed is not done at the moment is to remember the selection of verses per tab. That could be improved.

**Comment by toazd** [comment]
The functionality to restore scroll position appears to work fine.

One thing that frustrated me was when I was trying to compare (in two different tabs) two different words (with their strongs definitions shown in the open dictionary) in different books and verses . Every time I swap tabs I have to reselect the verse and highlight the word. And that made me curious if it was possible to keep the tabs loaded.

**Comment by toazd** [comment]
I noticed a little bit ago that if I click "find all occurrences", the search tab opens with the results as you would expect, however when I switch back to the bible tab that I was using the scroll position is reset back to the top. I tried it with two different sources and the scroll position is reset to the top for both.

**Comment by tobias-klein** [comment]
> I noticed a little bit ago that if I click "find all occurrences", the search tab opens with the results as you would expect, however when I switch back to the bible tab that I was using the scroll position is reset back to the top. I tried it with two different sources and the scroll position is reset to the top for both.

This is definitely a bug. Thank you for reporting it. I just opened issue #1101.
