### ISSUE TITLE
Font settings only affect the main window

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1099]
Changing font settings like typeface and size does not appear to affect the left pane/window (note/books/etc.).

Is there a way to customize the typeface and size on the left side?

**Comment by tobias-klein** [comment]
The typeface can currently only be configured for Bible text.
This is applicable both for the main Bible text area as well as for the compare translation function in the side panel.

The font size settings can be applied either only for the Bible text window as well as for the side panel. The setting for the side panel is called *Adjust side panel font size*. This option can be found under the Display group of settings.

![image](https://github.com/user-attachments/assets/cdf64890-d2ca-419d-b783-5f37d9825c73)

Something we could do is add a checkbox in the type face dialog that determines whether the type face settings should be applied only to Bible text or also to other types of content.

**Comment by tobias-klein** [comment]
@toazd Any further feedback?
