### ISSUE TITLE
Lost file permissions? 

### ISSUE THREAD

**Issue by greg-hellings** [ezra-bible-app/ezra-bible-app#1167]
I've been using Ezra for a while on my phone. Opened it today and got this message: 
![Screenshot_20241222-111656](https://github.com/user-attachments/assets/41414d80-2f88-4fcd-976c-3584da9ef2a2)

It has not been denied any permissions. The settings page for the app doesn't show it requesting any permissions related to files anymore. I've installed it through Obtanium on GrapheneOS, in case that is relevant. Version 1.15.0

**Comment by tobias-klein** [comment]
> I've been using Ezra for a while on my phone. Opened it today and got this message: 
> 
> It has not been denied any permissions. The settings page for the app doesn't show it requesting any permissions related to files anymore. I've installed it through Obtanium on GrapheneOS, in case that is relevant. Version 1.15.0

Hi @greg-hellings!

Thanks for getting in touch regarding this issue. Mmmm... I am a bit puzzled what happened here. GrapheneOS is a runtime environment I am not familiar with. Is it possible to change the storage permissions through the system settings dialogue specific for the app?

Did you add any user data (notes or tags)? If not, then you could try to uninstall the app including the removal of user data. In that case your problem should be solved when re-installing the app.

On vanilla Android, the approach with the granting of settings and storing files on the user accessible storage under /sdcard changed in Android 12. In Ezra, there is therefore a different behavior depending on the Android version (< 12 vs >= 12). In versions >= 12, everything is stored in the app directory (only accessible by the app itself), while in versions < 12, the SWORD directory as well as the user database is stored under /sdcard. What version of Android does this GrapheneOS environment map to?

**Comment by greg-hellings** [comment]
This version is running Android 15, and it had been getting all the data previously. There have been some updates to GrapheneOS since I last had launched the app, so that is where the change likely lives. But here is the app settings page. Android doesn't even think it is asking for file permissions anymore. 
![Screenshot_20241222-135901](https://github.com/user-attachments/assets/6584062e-bb35-4067-9bad-8728bb959e0b)

**Comment by greg-hellings** [comment]
I just tried to remove and reinstall the app. This time it picked up the 1.15.2 Android APK, but it's still giving me the error about permissions when I try to enable file access at the launch screen. Somehow the way the app is asking for permissions isn't being understood by this latest version of Graphene.

**Comment by tobias-klein** [comment]
> I just tried to remove and reinstall the app. This time it picked up the 1.15.2 Android APK, but it's still giving me the error about permissions when I try to enable file access at the launch screen. Somehow the way the app is asking for permissions isn't being understood by this latest version of Graphene.

With an environment that maps to Android 15, the app should not be asking at all for permissions. Maybe the mechanism for detecting the Android version is not working. What we could is completely disable the external /sdcard storage even for Android versions < 12.

**Comment by tobias-klein** [comment]
@greg-hellings 
This is the JavaScript code in `app/frontend/platform/cordova_platform.js` that determines the Android version:

```JavaScript

  getAndroidVersion() {
    var userAgent = navigator.userAgent.toLowerCase(); 
    // eslint-disable-next-line no-useless-escape
    var match = userAgent.match(/android\s([0-9\.]*)/i);
    var version = match ? match[1] : undefined;

    if (version !== undefined) {
      version = parseInt(version, 10);
    }

    return version;
  }
```

Maybe the navigator.userAgent returns something else with the result that the version cannot be matched?

**Comment by tobias-klein** [comment]
@greg-hellings
Could you open https://www.whatsmyua.info/ on your phone and tell me what you get as user agent string?

**Comment by greg-hellings** [comment]
So the useragent library responds that I'm running Android 0.0.0 while the other libraries on that page report Android 10, which is in keeping with the actual content of the User Agent string. GrapheneOS's benefit is that it tries to make you as in control of your anonymity as possible. Part of that is the built in browser has a frozen user agent string that is frozen to Android 10. Just this past week an update to the embedded browser display library was shipped, and I bet they updated it to also have the same frozen UA string for the same privacy reasons. Is there a way to directly query a system API for that information instead of relying on the Agent?

**Comment by greg-hellings** [comment]
The exact user agent is `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36`

**Comment by tobias-klein** [comment]
> So the useragent library responds that I'm running Android 0.0.0 while the other libraries on that page report Android 10, which is in keeping with the actual content of the User Agent string. GrapheneOS's benefit is that it tries to make you as in control of your anonymity as possible. Part of that is the built in browser has a frozen user agent string that is frozen to Android 10. Just this past week an update to the embedded browser display library was shipped, and I bet they updated it to also have the same frozen UA string for the same privacy reasons. Is there a way to directly query a system API for that information instead of relying on the Agent?

Querying a system API is only possible through the Cordova framework.

I may try with this Cordova plugin:
https://cordova.apache.org/docs/en/11.x/reference/cordova-plugin-device/

That plugin has a device.version API.

Let me check whether this works. If so, I could integrate this in the upcoming release 1.16.

**Comment by tobias-klein** [comment]
The cordova-plugin-device does not install successfully ...

**Comment by greg-hellings** [comment]
Bummer. I was just scouring its source code and it looks like it's exactly perfect.

**Comment by tobias-klein** [comment]
> Bummer. I was just scouring its source code and it looks like it's exactly perfect.

Yes, I thought so, too. When installing it I got this very "clear" error message ...

```
Installing "cordova-plugin-device" for android
Error: warn
```

The other things we could do:

* Eliminate this Android version differentiation completely, but that would be to the disadvantage of existing users with Android versions < 12.
* Develop a custom Cordova plugin that only reads the Android version.

**Comment by tobias-klein** [comment]
@greg-hellings
I managed to integrate [cordova-plugin-device](https://cordova.apache.org/docs/en/12.x/reference/cordova-plugin-device/) and reshaped the version check accordingly, so that it does not rely on the user agent any longer, but on the internally available Android version.

To make this work I head to do some heavy-lifting in [ezra-bible-app-cordova](https://github.com/ezra-bible-app/ezra-bible-app-cordova):
- Upgrading from Cordova 7 to Cordova 12
- Upgrading from Cordova Android 6.4 to [13.0](https://cordova.apache.org/announcements/2024/05/23/cordova-android-13.0.0.html)
- Upgrading nodejs-mobile-cordova from the last version that was maintained by Janea Systems to a [new version](https://github.com/okhiroyuki/nodejs-mobile-cordova) based on a [community fork of nodejs-mobile](https://github.com/nodejs-mobile/nodejs-mobile).
- Making changes in my Build environment for ezra-bible-app-cordova:
  - Moving to a new Java version (from 8 to 17)
  - Moving to a new Gradle version (from 6.7.1 to 7.6)
  - Moving to a new Android NDK (from 21.3 to 27.2)
 
This should then be released as part of Ezra Bible App 1.16. The release should happen soon, currently I am still waiting for updates from the translators.

**Comment by tobias-klein** [comment]
@greg-hellings The new app version is published in Google Play. Could you confirm that the problem is solved?

**Comment by greg-hellings** [comment]
Obtanium picked it up last night and today it is working flawlessly, with the data still intact from the original install. Thanks!

**Comment by tobias-klein** [comment]
> Obtanium picked it up last night and today it is working flawlessly, with the data still intact from the original install. Thanks!

Excellent, that to hear that! 
Have a blessed start into the new year!
