### ISSUE TITLE
Text to speech feature

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#138]
This has been requested by a user on the [user forum](https://forum.ezra-project.net/topic/2/user-forum-established/4).

**Comment by sammyj85** [comment]
I think this would be a valuable feature, if the capacity for development is there.

A basic level would be using eSpeak NG (https://github.com/espeak-ng/espeak-ng). This may be the easiest, especially for multiple languages. I have heard it used in another Bible app (can't remember which one), but it is admittedly robotic and difficult to understand.

A potentially more complex option in Coqui.ai (https://github.com/coqui-ai/TTS), which sounds amazing. Try the Reference Audio: https://huggingface.co/spaces/coqui/xtts. This would be amazing for an audio Bible. I haven't looked into incorporating it into anything yet myself.

**Comment by tobias-klein** [comment]
This may be interesting, but not something I will put on my list of things to do. If something else volunteers to implement such a feature I would gladly support!
