### ISSUE TITLE
Windows 7: No shortcuts created during install

### ISSUE THREAD

**Issue by DavidHaslam** [ezra-bible-app/ezra-bible-app#167]
The installation of Ezra Project on my Win7 PC did not result in the creation of an app shortcut anywhere - whether Start Menu, Desktop or Taskbar.

Nor were there any UI tick boxes to offer these options to the user.

**Comment by tobias-klein** [comment]
Windows 7 not fully supported even by Microsoft anymore. Not planning to fix this.
