### ISSUE TITLE
Add integrated online help that gives an overview for all keyboard shortcuts

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#198]
The information could be integrated in a separate tab of the info dialogue, or in a separate dialogue via a separate button.

Since the shortcuts are platform-specific (at least the CTRL vs CMD key, the content needs to a bit dynamic based on the platform. CTRL is used on Windows and Linux, while CMD is used on macOS.

The following shortcuts need to be documented:

| Summary                                        | Shortcut                                                                           |
| ------------------------------------------- | ---------------------------------------------------------------------- |
| In tab search                                  | CTRL/CMD + f                                                                 |
| Hide in tab search form                  | ESC                                                                                 |
| Jump to next search occurance     | Enter                                                                                |
| Jump to previous occurance          | Shift + Enter                                                                     |
| Copy selected verses to clipboard | CTRL/CMD + c                                                                 |
| Toggle fullscreen (only Win/Linux) | F11                                                                                   |
| Enable dynamic Strong's display   | Shift + mouse over verse while dictionary info is opened |
| Open new tab                                | CTRL/CMD + t                                                                  |

The texts need to be localized.

Short cut references of other software can serve as an inspiration.

**Comment by zhuiks** [comment]
Shortcuts for #42 Adjustable font size:
| Summary | Shortcut |
| ------------- | ----------- |
| Increase current font size | `CTRL/CMD +` |
| Decrease current font size | `CTRL/CMD -` |
| Reset font size to default | `CTRL/CMD 0` |

**Comment by augustin-colesnic** [comment]
**I picked this up. WIP**
Pushing first changes as in the screenshot attached:

<img width="832" alt="Keboard Shortcuts tab" src="https://user-images.githubusercontent.com/592416/119560248-5e5b5300-bdac-11eb-96fa-92306f21ab6b.png">

**Comment by augustin-colesnic** [comment]
Aaaaahhh! I forgot to create a feature branch and i committed on my forked master. 
Is it ok to create a PR from my forked master?

**Comment by augustin-colesnic** [comment]
pls Review MR https://github.com/ezra-bible-app/ezra-bible-app/pull/316

**Comment by tobias-klein** [comment]
Nice! I'll give feedback in the PR!
