### ISSUE TITLE
Module Install Assistant: default/favorite languages on top

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#201]
It would be nice to have default system language/app locale to display above all other languages, as well as languages for already installed modules

![Screenshot from 2021-03-23 10-51-18](https://user-images.githubusercontent.com/3584119/112218924-576c6480-8bf2-11eb-8a39-a9423188eeef.png)

**Comment by tobias-klein** [comment]
Good idea!
