### ISSUE TITLE
Module repository logos and links

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#202]
It would be nice to have information from which repository each module is. Maybe mark each module with repository logos? 
Logos can be first introduced in step 1 and displayed in step 3 for each module
Is there a link to that module on repository? If I want to see more details about development of that module and possibly contribute, how can I find where is it from and?

![Screenshot from 2021-03-23 10-53-42](https://user-images.githubusercontent.com/3584119/112219418-f1cca800-8bf2-11eb-9fe7-036b21ab7b2b.png)

**Comment by tobias-klein** [comment]
Good idea!
Getting the information from which repository a module is coming from is not so straightforward with SWORD ... but we can work our way around it. I will create an issue on node-sword-interface to add some support code there first.

**Comment by tobias-klein** [comment]
Here is a link to the newly created issue on node-sword-interface:
https://github.com/ezra-project/node-sword-interface/issues/10

Regarding the logos ... not sure whether something like that is available at this point. Here is a wiki page about all the repositories:
https://wiki.crosswire.org/Official_and_Affiliated_Module_Repositories

Maybe it would be worthwhile to check with the people on the [sword-devel mailing list](https://www.crosswire.org/mailman/listinfo/sword-devel)?!
