### ISSUE TITLE
Locale switch

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#203]
It would be nice to have locale switch. My system locale is English, but I would like to use the app in Ukrainian localization

**Comment by tobias-klein** [comment]
Yes, I agree that this would be useful! Other frontends implement this as well I believe.

**Comment by tobias-klein** [comment]
@zhuiks
How about planning this for 0.19.0? Could you imagine implementing this?

**Comment by alerque** [comment]
This is typically handled by an environment variable: something that can be set on a per command basis as well. You can almost certainly do this now without any changes by launching with `LANG=uk ezra-project`.

**Comment by tobias-klein** [comment]
Yes, launching with environment possible should work. And right now system settings are already considered. However, overriding the system settings is the intention of this feature, I think.

**Comment by zhuiks** [comment]
> @zhuiks
> How about planning this for 0.19.0? Could you imagine implementing this?

Yes, I can plan on implementing it for 0.19.0

> Yes, launching with environment variable should work. And right now system settings are already considered. However, overriding the system settings is the intention of this feature, I think.

Yes, that is the intent. When people are bilingual they might have different locale preferences for particular program that is different from their system locale. In my case, I like to keep my system Ubuntu locale in English, because it's a nice default. But Ezra Bible App I want to use in Ukrainian. I think mostly because of the book names... Hmm, maybe we should change book names menu depending on the language of the module?

**Comment by tobias-klein** [comment]
This is how the language list looks on Android (hadn't it tested there before):

![image](https://user-images.githubusercontent.com/17739895/119400437-782c6580-bcda-11eb-9c71-793ad1399f90.png)

**Comment by zhuiks** [comment]
The cause is `Intl.DisplayNames()`. It's a newer object.
On which Android/WebView version is it? It should be good starting from WebView 81:
![Screenshot from 2021-05-24 15-04-23](https://user-images.githubusercontent.com/3584119/119402992-55328f00-bca3-11eb-879d-85b3f918ecf3.png)

Probably updating [WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_IN&gl=US) is not a good option for the end user. What is the minimal Android version we are supporting?

Anyway, I'll just add a fallback to language mapper.

**Comment by tobias-klein** [comment]
> On which Android/WebView version is it? It should be good starting from WebView 81:

This is actually Android 10 with Chromium/Webview version 90.

We support Ezra starting from Android 5 with upgraded Webview. The minimum Webview is the one supporting EcmaScript 2017, which is version 55. This is codified in platform_init.js.

**Comment by zhuiks** [comment]
> This is actually Android 10 with Chromium/Webview version 90.

Hmm..., That's  strange. I guess I have to figure out that Cordova build till the end to test it there.

Thanks for the info

**Comment by tobias-klein** [comment]
I recently updated the Cordova README with more information on how to set things up ... Maybe that helps!

**Comment by tobias-klein** [comment]
@zhuiks 
The Cordova startup is fixed now ... you can check it out there.

**Comment by zhuiks** [comment]
Thanks 👍

**Comment by tobias-klein** [comment]
@zhuiks What needs to be done to fix this?

**Comment by zhuiks** [comment]
Thanks for reminding me to follow up on that.
From my findings only Android 11 has `Intl.DisplayNames`. You can confirm that by checking `typeof Intl.DisplayNames` with `chrome://inspector`.
I did a major refactor of languageMapper and it will fall back to the English language names when there is no DisplayNames is not avaliable under Internationalization API

**Comment by tobias-klein** [comment]
@zhuiks 
I found another issue.

This is on Android after switching to a different language (in this case from German to English).

![image](https://user-images.githubusercontent.com/17739895/122460417-60cb5a00-cfb2-11eb-95f8-1e25bfbb90c8.png)

**Comment by zhuiks** [comment]
> This is on Android after switching to a different language (in this case from German to English). There are no JavaScript errors, though.

Which version of Android?

**Comment by tobias-klein** [comment]
Android 10

**Comment by zhuiks** [comment]
Hmm... That what I have on my Emulator. Do you mind checking what do you get in `chrome://inspect` console for `Intl.DisplayNames` or `(new Intl.DisplayNames('de', { type: 'language', fallback: 'none' })).of('uk')` on that device?

**Comment by tobias-klein** [comment]
```
Intl.DisplayNames
ƒ DisplayNames() { [native code] }
```
```
(new Intl.DisplayNames('de', { type: 'language', fallback: 'none' })).of('uk')
undefined
```

**Comment by tobias-klein** [comment]
Mmmm... I only see this issue after switching back to English.

**Comment by tobias-klein** [comment]
After switching to other languages I don't see any parentheses after the language name.

**Comment by zhuiks** [comment]
Ok, it wasn't an issue with Android. `LanguageMapper` was working correctly. But I made a mistake in logic in `i18nHelper.getLanguage()`. Hope that's resolves the issue for good :grin:
