### ISSUE TITLE
Select verse range by SHIFT + click

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#215]
It's a typical behaviour to select a range with one item already selected by holding SHIFT and click on another item. This will select the range between two items (verses)

**Comment by tobias-klein** [comment]
Yes, I am familiar with this pattern, too. And I agree that it would be useful!
However, with the current implementation we need to figure out whether this can be implemented based on the existing JQuery UI Selectable API, see https://api.jqueryui.com/1.8/selectable/ and the respective code in the [VerseSelection](https://github.com/ezra-project/ezra-project/blob/master/app/frontend/components/verse_selection.js#L42) component.

**Comment by tobias-klein** [comment]
This has been implemented in version 1.13  (see #957)
