### ISSUE TITLE
Localized language list and emoji categories and annotations

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#230]
[CDLR](https://github.com/unicode-org/cldr-json) is the canonical source of locale data for a lot of software. It would be nice to use it for the language list in the Module assistant and for emojis annotations (search) and categories. Maybe there would be other data that can be localized in the future (units?). 

I found this library that might be helpful: [globalize js](https://github.com/globalizejs/globalize)

**Comment by alerque** [comment]
Using CLDR data for localized language names and a few other single word type translations lists. I'm less sure about *globalize*. I'm quite out of touch with Javascript development these days but I am active in a number of translation systems and literally the only that I can endorse is Fluent. I know there is a mature Javascript implementation (two in fact, one canonical reference and one faster and more Javascript idiomatic one for production use). Is there any chance of using Fluent for all l10n/i18n tasks? I know there is a pretty simple key/val system in place with a few languages already, but before you start adding more localization effort I think it would be good to consider whether the framework is the best one to be using. As strings proliferate and get more complicated the simple key/value systems start falling down on the job, and the more they are entrenched in development the harder it is to switch later. Adding yet another l10n framework (even if it's just used for some bits like language menus) just digs in further.

**Comment by zhuiks** [comment]
Thanks for sharing.

> Software localization has been dominated by an outdated paradigm: the translation is just a dictionary of strings which map one-to-one to the English (en-US) copy. This paradigm is unfair and limiting to languages with grammars more complex than English. For any grammatical feature not supported by English, a special case must be added to the source code, leaking logic into all translations. Furthermore, creating good UIs which depend on multiple external arguments is hard and requires the developer to understand the grammar of the languages the product targets.

I can definitely  agree with that. Current well-known framework **i18next** is using string matching approach. Having translated Ezra project interface into Ukrainian/Russian I struggled with strings like `Ezra Bible App works with {{module_type}} provided by ...` Both Ukrainian and Russian have cases and noun `{{module_type}}` changes depending how it used in the sentence. **Fluent** seems to address this kind of issues.

However I think the development cost of switching from **i18next** to **Fluent** is quite high. But it definitely worth of separate issue.

From my brief review of Project Fluent documentation it doesn't address the issue topic on how to use already defined data for localized [language list](https://github.com/unicode-org/cldr-json/tree/master/cldr-json/cldr-localenames-full/main) and emoji [categories](https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-misc-full/main/en/characterLabels.json) and [annotations](https://github.com/unicode-org/cldr-json/tree/master/cldr-json/cldr-annotations-full/annotations) (text representations used to search for emoji)

**Comment by zhuiks** [comment]
I found that localized languages in such high demand that they are making it to the [JavaScript standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames):
```
Intl.DisplayNames()
```

We are good with Chromium (Electron) and Android Webview (Cordova)

**Comment by zhuiks** [comment]
Emoji annotations are done.
New issue #272 is more descriptive about language list
