### ISSUE TITLE
Book list in Ukrainian/Russian

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#233]
Book names that have numbers in their title are not listed as grammatically correct.
It should be "1-e Коринтян" instead of "1. Коринтян" and so on: 
![Знімок екрану з 2021-04-22 08-40-48](https://user-images.githubusercontent.com/3584119/115879219-0927cc80-a40f-11eb-9e97-66ccd147db4a.png)

**Comment by zhuiks** [comment]
I know, book names are coming from Sword API. So I'll try to resolve it within Sword mailing list.

**Comment by tobias-klein** [comment]
Here is a mirror of the SWORD sources on GitHub (I am taking SWORD from there):
https://github.com/bibletime/crosswire-sword-mirror/

The respective file should be this one:
https://github.com/bibletime/crosswire-sword-mirror/blob/trunk/locales.d/uk-utf8.conf

I am copying the locales.d folder occasionally to node-sword-interface here:
https://github.com/ezra-bible-app/node-sword-interface/tree/master/locales.d

I would suggest to submit a patch to the SWORD maintainers (via the SWORD mailinglist). Sword is maintained in SVN here:
https://crosswire.org/svn/sword/trunk/

You can `svn checkout` from there .... make your fixes in the locales.d file ... then generate a patch and submit that patch to the SWORD mailinglist.

**Comment by zhuiks** [comment]
Thank you!

**Comment by tobias-klein** [comment]
Let's put this on 1.1!

**Comment by zhuiks** [comment]
I think once you update node-sword-interface it should be already there.

**Comment by zhuiks** [comment]
> I suppose we can close this issue?

Yes
