### ISSUE TITLE
Icon-based note indicators not synchronized with multiple tabs

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#234]
The new icon-based note indicators are not synchronized across multiple tabs. This is a necessary function when you have the same verse opened in multiple tabs whether it's a book or matching search results or tagged verses that overlap with an existing verse box.

This is solved for the note text itself as well as for tags already. The same helper function could be used to support replicating the note indicators. This is the helper function: [VerseBoxHelper.iterateAndChangeAllDuplicateVerseBoxes()](https://github.com/ezra-bible-app/ezra-bible-app/blob/master/app/frontend/helpers/verse_box_helper.js#L94).

Examples for how this is used:
https://github.com/ezra-bible-app/ezra-bible-app/blob/master/app/frontend/controllers/notes_controller.js#L93

**Comment by tobias-klein** [comment]
@zhuiks Would you mind taking a look at this?

**Comment by zhuiks** [comment]
Ok, I'll look at it
