### ISSUE TITLE
Tag categories

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#235]
Categories for tags would allow to filter the tags and their associated verses in a more refined way.

There could be some default categories like the following:
- Topic
- Doctrine
- Phrase
- Sermon / Bible Study
- Grammar / Style

The list of categories could be editable.

Any given tag could be associated with 0 or 1 category.

**Comment by tobias-klein** [comment]
Technically yes, but I think the category list should be separate and that would be a separate feature.

**Comment by zhuiks** [comment]
Another idea is to use a special tag category to display as custom headings. Initial "heading tags" can be imported from the module headings (#224). 
Kind of having personal outline... (wasn't that the original functionality?)

**Comment by zhuiks** [comment]
I also think that categories should be color-coded. It's an easy way to visualize categories

**Comment by tobias-klein** [comment]
This is obsolete based on the tag groups feature, which can be used to support the requirements described here.
