### ISSUE TITLE
Responsive dictionary window

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#240]
I think the dictionary window should be a bit more responsive for smaller window sizes:
![Знімок екрану з 2021-04-29 16-22-29](https://user-images.githubusercontent.com/3584119/116620204-22e17c00-a907-11eb-94de-235da65111e5.png)

**Comment by tobias-klein** [comment]
I agree to your observation! The vertical size of the dictionary box is managed within [`UiHelper.resizeAppContainer`](https://github.com/ezra-bible-app/ezra-bible-app/blob/master/app/frontend/helpers/ui_helper.js#L161).
