### ISSUE TITLE
Inconsistent cached Bible book list

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#275]
I still didn't nail down the pattern. But somehow when I switch locales back and force I'm ending up with the English Bible book list getting pulled from cache on app start instead of my system locale which is Ukrainian.

**Comment by tobias-klein** [comment]
Yeah, I have also seen some issues with this before when switching languages via the system settings. I guess the best thing would be:

* Rewrite the cache whenever the language has changed in the app.
* Rewrite the cache whenever the language on app start is different than the last used language.

**Comment by zhuiks** [comment]
> * Rewrite the cache whenever the language has changed in the app.
> 
> * Rewrite the cache whenever the language on app start is different than the last used language.

Shouldn't it be only one locale setting in the settings file?
Currently in settings there are `appLocale` to keep track of selected locale and `lastUsedLanguage` used for checking validity of cache.

Why `lastUsedLanguage` setting is included via `settings_storeLastUsedLanguage` in [`ipc_settings_handler`](https://github.com/ezra-bible-app/ezra-bible-app/blob/e3b7de683e53354128858f526022c47fe5a597a5/app/backend/ipc/ipc_settings_handler.js#L113) ?

**Comment by tobias-klein** [comment]
> Shouldn't it be only one locale setting in the settings file?
> Currently in settings there are `appLocale` to keep track of selected locale and `lastUsedLanguage` used for checking validity of cache.
> 
> Why `lastUsedLanguage` setting is included via `settings_storeLastUsedLanguage` in [`ipc_settings_handler`](https://github.com/ezra-bible-app/ezra-bible-app/blob/e3b7de683e53354128858f526022c47fe5a597a5/app/backend/ipc/ipc_settings_handler.js#L113) ?

Well, currently lastUsedLanguage is used to check the validity of the cache. `appLocale` is new and not present on `master` yet. Now that we are introducing `appLocale` on the feature-locale-option branch we can probably drop `lastUsedLanguage`.
