### ISSUE TITLE
Refactoring: Use observer pattern for events currently handled by AppController

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#282]
We could use the observer pattern for handling these events:

* tab search results available => currently `AppController.onTabSearchResultsAvailable`
* tab search reset => currently `AppController.onTabSearchReset`
* tab selected => currently `AppController.onTabSelected`
* tab added => currently `AppController.onTabAdded`
* bible translation changed => currently `AppController.onBibleTranslationChanged`
* all translations removed => currently `AppController.onAllTranslationsRemoved`
* translation removed => currently `AppController.onTranslationRemoved`

This currently corresponds to ~200 lines of code in `AppController` ... which would then mostly move to the respective components that respond to these events.

**Comment by tobias-klein** [comment]
@zhuiks Any thoughts on this?

**Comment by zhuiks** [comment]
Big yes for refactoring! AppController and TabController were really hard to figure out what runs after what and what runs only at start up.

However, I think refactor Tab to tab web component should come first. It can be 3-4 components based on tab type with common base tab component. 
Also the decision needs to be made about state management. Having clearly defined state object/objects helps to understand component dependencies on the state parts. Observer pattern by itself doesn't provide that clarity.

**Comment by zhuiks** [comment]
My thoughts:
 
The new `eventController` will have the implementation of the observer pattern.

Each component that generates the event should create with the help of `eventController` and export an appropriate subscription method (i.e. `onTranslationRemoved`) and notify all subscribers by triggering something like `eventController.trigger('TranslationRemoved')`

Each subscriber component would subscribe with that method:
```javascript
app_controller.moduleAssistatant.onTranslationRemoved(() => {
  // do something inside the subscriber component
});
```

That way we will have the central implementation. But at the same time, all components would be responsible for their events. And we would have a descriptive name for the subscription.

**Comment by tobias-klein** [comment]
Good design ideas! I could imagine a design like that!
The design pattern is essentially like a central "message bus" for events.
