### ISSUE TITLE
Improve dev work with CSS preprocesor like Sass

### ISSUE THREAD

**Issue by augustin-colesnic** [ezra-bible-app/ezra-bible-app#319]
It will be great improvement for the development if we use a **CSS pre-processor like Sass** for  theming the App.

**Comment by zhuiks** [comment]
I understand you got that urge to do something by looking inside `main.css` :smile: 
I agree we have to do something with it. I think benefits of SASS/SCSS would be scoping and use of variables for "theming" (color,font-style, etc.)

For scope our goal is to refactor `main.css` file and to move most of the styles to individual web-component files. Please take a look at [`configOption`](https://github.com/ezra-bible-app/ezra-bible-app/blob/0a2e8c490564403cfa14ee58fb23e5d81b685e64/app/frontend/components/config_option.js#L22), [`localeSwitch`](https://github.com/ezra-bible-app/ezra-bible-app/blob/0a2e8c490564403cfa14ee58fb23e5d81b685e64/app/frontend/components/locale_switch.js#L27) and [`emojiButtonTrigger`](  https://github.com/ezra-bible-app/ezra-bible-app/blob/0a2e8c490564403cfa14ee58fb23e5d81b685e64/app/frontend/components/emoji_button_trigger.js#L25). 
Just recently we decided that it would be a good idea to use HTML custom elements to have markup, style and logic in one place for individual components (initial discussion #251).
If we choose to use additional library, like [Lit-elements](https://lit.dev/docs/components/styles/) it can be simpler to work with styles. Please feel free to add your input to the discussion mentioned above.

For theming variables we could (should!) use vanilla [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

**Comment by augustin-colesnic** [comment]
Thanks Evgen! I will close this issue then and engage on the discussion #251
