### ISSUE TITLE
Labels in menu are wrapping when loading text

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#325]
When loading new text the labels in the menu are wrapping the text across multiple lines. This should not happen - it looks ugly. This is visible for the last row of labels/buttons in the menu and seems to be influenced by the dynamic showing of the text loading indicator.

This has been observed on a 7" tablet screen (see screenshot below).

![image](https://user-images.githubusercontent.com/17739895/120107949-49434300-c163-11eb-9230-1f0548276599.png)

**Comment by tobias-klein** [comment]
@zhuiks Would you mind looking into this?

**Comment by zhuiks** [comment]
Does this happen only in the last row?

**Comment by tobias-klein** [comment]
> Does this happen only in the last row?

Yes! And the root cause seems to be the loading indicator that pushes things to the left once it's shown.

**Comment by tobias-klein** [comment]
@zhuiks I just committed a simple style fix by using `position: fixed`

**Comment by zhuiks** [comment]
Thanks. 
I'll probably refactor loader to the separate component later and look one more time into this.
