### ISSUE TITLE
Missing chapter title for modules without embeded chapter titles

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#329]
NET Ephesians:
![Screenshot from 2021-06-01 13-51-14](https://user-images.githubusercontent.com/3584119/120379321-33f62200-c2e5-11eb-91fc-8b7329efa3ce.png)

RSP Psalms:
![Screenshot from 2021-06-01 13-53-58](https://user-images.githubusercontent.com/3584119/120379331-35bfe580-c2e5-11eb-8d4d-cadee9e54fe8.png)

KJV Psalms (title is shown because KJV has that emebeded):
![Screenshot from 2021-06-01 13-55-34](https://user-images.githubusercontent.com/3584119/120379338-38223f80-c2e5-11eb-9988-84359c3f29ae.png)

**Comment by zhuiks** [comment]
I think it's an issue in [`textController`](https://github.com/ezra-project/ezra-project/blob/59a0e7cfe85c0577110128b753748549fe7d1afd/app/frontend/controllers/text_controller.js#L270) 
```javascript
    var verses_as_html = verseListTemplate({
      versification: versification,
      verseListId: current_tab_id,
      renderVerseMetaInfo: true,
      renderBibleBookHeaders: false,
      // only render chapter headers with the full book requested
      renderChapterHeaders: (start_verse_number == -1), //  <-- Seems like it becomes true very seldom
      renderBookNotes: (start_verse_number == 1),
      bookIntroduction: bookIntroduction,
      bookNotes: bookNotes,
      bibleBooks: [bibleBook],
      verses: verses,
      verseTags: verseTags,
      verseNotes: verseNotes,
      marked: this.marked,
      referenceSeparator: separator,
      chapterText: book_short_title === 'Ps' ? "bible-browser.psalm": "bible-browser.chapter",
      helper: {
        getNotesTooltip: notesHelper.getTooltipText,
        getLocalizedDate: i18nHelper.getLocalizedDate,
      } 
    });

```

**Comment by tobias-klein** [comment]
Thanks for reporting this!

**Comment by tobias-klein** [comment]
This regression bug was introduced with version 0.13.0.
