### ISSUE TITLE
Repositories not loaded on Android Ezra Bible App v.1.0.1

### ISSUE THREAD

**Issue by augustin-colesnic** [ezra-bible-app/ezra-bible-app#330]
### but cannot proceed with first step as repositories are not loaded.
![Screenshot_20210602-093048_Ezra Bible App](https://user-images.githubusercontent.com/592416/120435334-43797780-c386-11eb-9e81-7834d71fa9cc.jpg)
![Screenshot_20210602-093547_Ezra Bible App](https://user-images.githubusercontent.com/592416/120435336-44aaa480-c386-11eb-801b-889da0458472.jpg)

**Comment by tobias-klein** [comment]
Thanks for reporting this. This worked in the Android emulator for 1.0.1, so I need to analyze based on the sources ...

**Comment by tobias-klein** [comment]
@augustin-colesnic
Would you mind providing another log file via logcat? That would greatly help!

**Comment by augustin-colesnic** [comment]
Sure, here it is @tobias-klein:


[debug_4_june_2021.txt](https://github.com/ezra-bible-app/ezra-bible-app/files/6596027/debug_4_june_2021.txt)

**Comment by tobias-klein** [comment]
Excellent, thanks!

Mmmm... seems like there are still paths that need to be corrected from external to internal storage.

```
06-04 08:44:12.829 10220 20626 I NODEJS-MOBILE: Initializing persistent IPC!
06-04 08:44:12.862 10220 20627 E NODEJS-MOBILE: Failed to create user sword dir at /sdcard/sword
06-04 08:44:12.864 10220 20627 E NODEJS-MOBILE: Failed to create module dir at /sdcard/sword/mods.d
```

That explains why the repository update does not work. I'll check in the code now ... if it's just about the paths it should be easy to fix ... and that that will be 1.0.2!

**Comment by tobias-klein** [comment]
So ... I ended up missing something in the fixes for 1.0.1 ... just pushed a fix. I still need to "smoke-test" this in the Android emulator and then push out 1.0.2 to the Play Store! Thanks once more for reporting this and providing the log file, having the log file available made it so much easier to find out what was going wrong exactly!

**Comment by tobias-klein** [comment]
@augustin-colesnic I have just pushed 1.0.2 to the Play Store for approval and will let you know once it is available!

**Comment by tobias-klein** [comment]
@augustin-colesnic
Version 1.0.2 is available in the Play Store now!
