### ISSUE TITLE
Android: Showing toolbar results in invalid / buggy layout

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#337]
This was observed on Android. When switching on the tool bar, I got this as a result ... and this feels like a regression (I don't think this is a bug in any release).

![Screenshot_2021-06-06-11-50-05-253~2](https://user-images.githubusercontent.com/17739895/120920225-21e9fa00-c6be-11eb-849a-5339d492858f.jpeg)

**Comment by tobias-klein** [comment]
@zhuiks Any idea what happened here?

**Comment by zhuiks** [comment]
@tobias-klein 
There is some bug in CSS. I'll refactor the whole layout under #302

**Comment by tobias-klein** [comment]
Ok!

**Comment by tobias-klein** [comment]
@zhuiks 
Can you check whether there is a quick fix for 1.1 - since we are not ready with #302 yet?

**Comment by zhuiks** [comment]
> @zhuiks Any idea what happened here? It seems like the space is reserved for the dictionary component. However, there is no dictionary component on Android!

I can't replicate this on emulator. But I added an extra check for Android in css.
@tobias-klein can you please check PR #374
