### ISSUE TITLE
Error messages on Android

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#344]
I'm getting the following error messages on Android Emulator (7", Android 10)
```
ezra_init.js:16218 Did not get node response for db_getLastMetaRecordUpdate
```
```
ezra_init.js:16218 Did not get node response for db_getAllTags
```

This is a new installation with few modules downloaded

**Comment by tobias-klein** [comment]
This happens when an IPC request runs into a timeout. Are you getting this with latest master? I've recently adjusted some of the timeouts.

**Comment by tobias-klein** [comment]
There maybe some more messages on the node backend side ... if you can reproduce this, can you attach the output of `adb logcat`?

**Comment by zhuiks** [comment]
This doesn't happen under master branch, only in PR #345
