### ISSUE TITLE
URLs in SWORD Module Description are not clickable

### ISSUE THREAD

**Issue by Berovowilare** [ezra-bible-app/ezra-bible-app#352]
Hello 

The URLs are not active links.

<img width="708" alt="Bildschirmfoto 2021-06-17 um 20 19 08" src="https://user-images.githubusercontent.com/36891575/122452201-4b9dfd80-cfa9-11eb-90d4-759f5a6bad56.png">

Thanks

**Comment by smpurkis** [comment]
I've made [PR 609](https://github.com/ezra-bible-app/ezra-bible-app/pull/609) to try and solve this.
