### ISSUE TITLE
macOS: Visible and to Use Modules

### ISSUE THREAD

**Issue by Berovowilare** [ezra-bible-app/ezra-bible-app#356]
Hello 

I can only see the Modules I have downloaded with Ezra. 
<img width="285" alt="Bildschirmfoto 2021-06-17 um 20 34 09" src="https://user-images.githubusercontent.com/36891575/122454327-90c32f00-cfab-11eb-882b-b43fd5640eb7.png">

In Eloquent I see now the Bibles I downloaded with Ezra too. 
<img width="204" alt="Bildschirmfoto 2021-06-17 um 20 36 03" src="https://user-images.githubusercontent.com/36891575/122454426-aafd0d00-cfab-11eb-9d38-fe9b5c9d179d.png">

But not otherwise.

Thanks

**Comment by tobias-klein** [comment]
Interesting observation! If Eloquent shows a superset of both sets of modules then Eloquent must read input from more than one path. I'll try to fix this in 1.2.

**Comment by Berovowilare** [comment]
I guess it simply shows what is in the SWORD folder.

**Comment by tobias-klein** [comment]
Mmmm... that's what Ezra does, too. It should be $HOME/.sword on macOS.
Can you check whether you find .sword folders in different places on your mac?

**Comment by Berovowilare** [comment]
Hmm. The Folder from Eloquent is in the Application Support. And the Bibles I downloaded via Ezra are not there. So it must be two folders. It seems Eloquent found the other too and included the modules.
Unfortunately I haven't found the folder of the modules of Ezra.
