### ISSUE TITLE
Repositories missing

### ISSUE THREAD

**Issue by theophiluso7** [ezra-bible-app/ezra-bible-app#359]
The repositories no longer even show up. Once a select a repository, it's gone forever. I tried uninstalling it (1.0) and reinstalling it. does not help. it remains the same. I installed by accident the dec 22 2020 build but i uninstalled it.
![image](https://user-images.githubusercontent.com/12585748/122462309-70cb4580-cf82-11eb-98fc-a96652fdc311.png)

**Comment by tobias-klein** [comment]
Thanks for reporting this. So, what happens when you press the "Update now" button?

**Comment by theophiluso7** [comment]
It works now. I unisntalled and removed ALL folders. I suspect it has something to do with me cancelling prematurely when Ezra was doing downloading or installing.
