### ISSUE TITLE
Use SWORD locale data as a fallback for Javascript i18n API

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#362]
As a fallback when Javascript i18n API not available or language code is not ISO-639.1 or ISO-639.2 code, it would be nice to use data from SWORD `locales.d/locales.conf` for language list in module assistant.

**Comment by zhuiks** [comment]
I think SWORD locale config should be compiled as a separate npm task to JSON to be used inside `localeMapper.getLanguageDetails` similar to `'iso-639-3'` library

**Comment by tobias-klein** [comment]
I guess the question is whether the benefit of this change justifies the effort ... :)

**Comment by zhuiks** [comment]
I think it's a good way to test out the setup for pulling data from SWORD to JSON which we can utilize for #304
