### ISSUE TITLE
Optimize emoji annotations and browserify

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#369]
Emoji annotations can be `required` dynamically, but that should be done in a separate file which should be excluded from browserify build
See https://github.com/ezra-bible-app/ezra-bible-app/pull/226#issuecomment-830739907

**Comment by zhuiks** [comment]
@tobias-klein 
Is Browserify used only for Cordova or other builds use it as well?

**Comment by tobias-klein** [comment]
> @tobias-klein
> Is Browserify used only for Cordova or other builds use it as well?

For a short period of time it was also used for the desktop (in version 0.17.0), but not anymore at this point.
