### ISSUE TITLE
Tag list not loading after starting from cache with tagged verse list

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#378]

**Comment by hashaway** [comment]
Hello Tobias,

I can confirm that I too am experiencing this issue. (Windows 7)

**Comment by tobias-klein** [comment]
It seems like the tag list will then only load once you freshly open a book.

**Comment by tobias-klein** [comment]
This is quite annoying. I think I'll try to fix asap and push out 1.1.1 as well asap.

**Comment by hashaway** [comment]
Yes, that is correct. It is doing exactly the same on my system.

I am very appreciative for all your work and the wonderful progress that you have been making.

**Comment by tobias-klein** [comment]
@hashaway Since this was discovered super short after the release this morning I just simply deleted and re-generated the release. Not super elegant from a configuration management perspective ... but better for the users :)

**Comment by hashaway** [comment]
I understand. Thank you for letting me know :)
