### ISSUE TITLE
Build process assumes Git clone, doesn't work from archive

### ISSUE THREAD

**Issue by alerque** [ezra-bible-app/ezra-bible-app#388]
Something in the last release cycle regressed and assumes all sources are Git clones.

There is a special Git attribute you can use to stuff git commit hash information automatically in `git archive` generated tarballs, but whatever is calling Git is trying to do so directly:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Interestingly it doesn't fail if it can't find the relevant Git repository, it just fails if `git` is not available. A assume there is a fallback somewhere for handling archive sources vs. clones, but the logic is wrong and shouldn't assume the availability of Git tooling if it isn't actually required to build.

See also #23 which is coming along but not quite there yet.

**Comment by tobias-klein** [comment]
Mmmm... I suppose the culprit could be the commit-info action that is run as a postinstall action via package.json. But this one was already in for 1.0.0, so it's not entirely new.

**Comment by alerque** [comment]
It *could* be that I neglected to check if the build worked in a chroot with only the declared dependencies available and instead tested on my host system that of course has Git. It should be a routine check but Electron packaging is always such a pain who knows what I might have skipped in my delirium.

**Comment by tobias-klein** [comment]
I'd be glad if you would contribute an alternative for pushing the last git commit hash into the build. Currently it's turned into a JS module at `app/commit_info.js` and then consumed by `app/frontend/components/info_popup.js`. The only thing extracted from it is the commit hash.

**Comment by tobias-klein** [comment]
> It should be a routine check but Electron packaging is always such a pain who knows what I might have skipped in my delirium.

Have you considered filing any issues with the [Electron project](https://github.com/electron/electron)?

**Comment by alerque** [comment]
> Have you considered filing any issues with the [Electron project](https://github.com/electron/electron)?

No. Even *knowing* how many distro packagers out there would consider me a hero, no.

**Comment by tobias-klein** [comment]
I just tested this in a Docker container without git and an archive of 1.2.0.

This is one of the remaining problems:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/zhuiks/emoji-button.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-01T18_28_43_027Z-debug.log
```

The root-cause is this dependency in package.json:

    "emoji-button": "github:zhuiks/emoji-button"

@zhuiks 
Can you release your fork of emoji-button on a package registry like npmjs.com?

**Comment by tobias-klein** [comment]
@alerque This should be fixed now. Can you try once more with latest `master`.
