### ISSUE TITLE
Strong's dictionaries are not automatically installed

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#404]
This is a regression bug. With the new module assistant, Bible translation modules that have Strong's should automatically trigger installation of default Strong's dictionaries. That's not happening now.

**Comment by tobias-klein** [comment]
@zhuiks If you have a chance to fix this before the 1.2.0 release I would greatly appreciate it.

**Comment by zhuiks** [comment]
I started digging into this. And figured out that the reason why Strongs dictionaries are not installed is that in [step_install](https://github.com/ezra-project/ezra-project/blob/bc64c33eecc9d3feb663225899de0420b203085b/app/frontend/components/module_assistant/step_install.js#L181)
``` javascript
 var strongsAvailable = await ipcNsi.strongsAvailable();
```
returns (resolves to) `true` even when none of the dictionaries are installed. The same is for `ipcNsi.greekStrongsAvailable()` and `ipcNsi.hebrewStrongsAvailable()`.

So I guess it's on node-sword-interface end. @tobias-klein would you mind checking?

I'm seeing this on Ubuntu 20, and I think it was the same on Android Emulator running on the same OS (see https://github.com/ezra-bible-app/node-sword-interface/issues/19).

**Comment by tobias-klein** [comment]
The root-cause was indeed in node-sword-interface and this is now fixed after updating to node-sword-interface 0.235.0.
