### ISSUE TITLE
Dictionary info: display a message when default Strong's dictionaries are not installed

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#405]
The dictionary functionality right now assumes that StronsGreek and StrongsHebrew modules are installed. Sometimes (#404) it's not the case. This should be handled properly with disabling Strong's word look up on Shift + mouse over or long press and the appropriate message should be displayed.

**Comment by tobias-klein** [comment]
Yes, this would be the clean solution - I agree.

Technically we could detect this on startup (I think I had that at some point) and then ask the user whether the Strong's dictionaries shall be installed. Of course this should only happen if the user has already installed any Bible modules that have Strong's support.

**Comment by zhuiks** [comment]
> Technically we could detect this on startup (I think I had that at some point) and then ask the user whether the Strong's dictionaries shall be installed. Of course this should only happen if the user has already installed any Bible modules that have Strong's support.

This would be better from UX perspective, but involves more efforts with implementation. Ideally, it should be handled with install assistant, including displaying internet usage note.

For now, I was thinking, just have a simple check in `dictionaryController` for the presence of Strong's dictionary modules. 
In the case of their absence, that would be the default message displayed in dictionary window in spite of whether Bible modules that have Strong's are installed.
