### ISSUE TITLE
Add button to toggle tab menu

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#407]
See discussion #349.

On smaller screens and also in general for more focus it would be nice to have a way to toggle the tab menu. This could be done with a small button directly underneith the full screen button.

**Comment by augustin-colesnic** [comment]
The fullscreen button itself should do that @tobias-klein. Tab menu should be removed on fullscreen mode.

**Comment by tobias-klein** [comment]
I can see your point, Augustin. However, the question is what functionality then remains in full screen. What you describe would be a read-only mode. Unless you provide the possibility of assigning tags via verse-based context menus. Even when going fullscreen I personally would still like to be able to assign tags.

**Comment by augustin-colesnic** [comment]
Yes, tags could be assigned only in full screen if we implement a better visualy UX/UI. I am thinking of a circle/ wheel of options when a verse is long pressed.

**Comment by tobias-klein** [comment]
Having to long press or right click on the desktop is only a last resort in my mind ... if somehow possible we should make most of the functionality available via regular left click / tap. Otherwise this will be rather hidden to first time users.

@augustin-colesnic Do you know a good and well maintained vanilla JS library that creates context menus?

**Comment by augustin-colesnic** [comment]
@tobias-klein  try these: https://www.cssscript.com/tag/circle-menu/
