### ISSUE TITLE
New sqlite3 causing issues

### ISSUE THREAD

**Issue by alerque** [ezra-bible-app/ezra-bible-app#436]
The current package.json calls for sqlite3 `^5.0.0`. This is causing [a build failure](https://github.com/alerque/aur/issues/23) in distro packages (at least when not bundling the system sqlite3, see #388 about that). @Sweenu noticed that locking that to `5.0.0` avoids the error:

```console
$ sed -i -e '/sqlite3/s/\^//' package.json
```

Obviously this isn't a permanent solution, just a pointer for figuring out where the problem might lie.

**Comment by tobias-klein** [comment]
I also noticed some issues related to sqlite3, specifically on macOS. However, those issues only occurred when re-building the native dependencies. So, most recently I actually disabled the `npm run rebuild` step in the build script of macOS. What happens in that case is that npm tries to download a pre-built binary. Maybe that's something you could try, too. Anyway - for the time being I locked the sqlite3 version to 5.0.0 as you suggested!

**Comment by alerque** [comment]
> What happens in that case is that npm tries to download a pre-built binary of the sqlite3 module and then that gets included when doing the packaging.

This is exactly the kind of thing distro's *don't* want to have happen in their packages. Building vendored sources is bad enough and only tolerated by some distros on a no-other-solutions-exist basis (others would flat refuse), downloading random binaries off the net during the middle of a build and bundling those is a bigger no-no.
