### ISSUE TITLE
Close tag assignment menu immediately after assign/unassign action

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#445]

**Comment by tobias-klein** [comment]
@zhuiks Instead of adding another option here the question is whether this could be default behavior. In that case we don't need to make it configurable. From a user perspective I rarely need to have the tag assignment menu stay open after assigning/unassigning a tag. So currently it requires at least three clicks to assign/unassign a tag (if the tag list is not shown permanently).

**Comment by tobias-klein** [comment]
@zhuiks Any feedback on this?

**Comment by zhuiks** [comment]
Yes, it makes sense to close tag menu as default behavior without extra option.
