### ISSUE TITLE
Auto-detected locale sometimes not matching with list of available locales

### ISSUE THREAD

**Issue by zhuiks** [ezra-bible-app/ezra-bible-app#467]
Currently, auto-detection locale returns 2-letter language and 2-letter region code (i.e. `en-US`). This string should be matched against a list of available locales to set the right language (i.e. `en`).
If locale available with region code (i.e. `pt-BR`) that should be the right match.

**Comment by zhuiks** [comment]
https://github.com/ezra-project/ezra-project/blob/45d07aee816c31adddd61f1f644f977a9b039e04/app/frontend/platform/i18next_browser_language_detector.js probably is the right place to do this check for both Electron and Cordova.

The following logic in `i18nController` can be moved to this universal languageDetector:
```javascript
  if (platformHelper.isElectron()) {
    LanguageDetector = require('i18next-electron-language-detector');
  } else {
    const _LanguageDetector = require('../platform/i18next_browser_language_detector.js');
    LanguageDetector = new _LanguageDetector();
  }
```

**Comment by tobias-klein** [comment]
Feel free to have a look! It'll be difficult for me this week.
