### ISSUE TITLE
Optimize tag ui in Change Tags menu (Rename, Delete)

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#475]
Rework the UI of each tag presented in the Change Tags menu. From a technical standpoint this could be a new web component.

Acceptance criteria:
* Use trash bin icon to delete tags
* Use edit icon to rename tags (replace previous mouseover functionality)

## Original proposal from @zhuiks 

I think that the editing should be in place. Without popup dialog. It can be triggered either by single/double tap (I think it's pretty common) or by "pencil" icon or both.
Instead of the checkbox, we can use "tag" icon that would be highlighted if the tag is assigned to the currently selected verse.

![Знімок екрану з 2021-10-04 15-31-35](https://user-images.githubusercontent.com/3584119/135929076-7fa2f755-d5ef-44e5-be7a-d4a18aee1ccc.png)

![Знімок екрану з 2021-10-04 15-39-45](https://user-images.githubusercontent.com/3584119/135929083-38c83f66-dd68-42d2-9036-5becc536b094.png)
I also think that "garbage can" icon is better for tag deletion than the "x" icon. The "x" icon can be confused with tag unassigment action.

_Originally posted by @zhuiks in https://github.com/ezra-bible-app/ezra-bible-app/discussions/447#discussioncomment-1427073_

**Comment by tobias-klein** [comment]
@augustin-colesnic @zhuiks 
Thinking about this, I am not sure whether the tag icon alone would suffice. Would it be intuitive for the user to click/tap on a greyed-out icon? Greyed-out often has the notion of "disabled". A checkbox on the other hand is a pretty clear interaction element that most users should already know. How about doing both - showing the checkbox *and* showing the tag icon?

**Comment by zhuiks** [comment]
We can try to make the label icon as a button (this would be just a matter of styling). So it would be obvious that user have to press it.

The other option would be a toggle switch component. It can be implemented as checkbox styling in pure CSS:
https://codepen.io/mburnette/pen/LxNxNg
The icon tag icon can be on top of the knob and change color depending either it's "on" or "off".

**Comment by tobias-klein** [comment]
Turning the label icon into a button-style element is something I can also imagine.
Using a toggle switch however does not match the metaphore of "assigning" something. To me, toggle switches are better suited for configuration/settings.

**Comment by tobias-klein** [comment]
I moved the "in-place editing" to a separate issue: #530
