### ISSUE TITLE
Menu keeps changing based on dynamic size of "Assign last tag" button

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#523]
Example 1
![image](https://user-images.githubusercontent.com/17739895/141675582-99a383ec-1787-4849-bc5c-e980af6cbea7.png)

Example 2
![image](https://user-images.githubusercontent.com/17739895/141675634-dda6dd95-bfba-4c4f-8bf1-7503c06ea157.png)

The menu keeps changing based on the dynamic size of the "Assign last tag" button. This is visible with the two examples above. This is happening without the window size changing and is certainly disrupting the workflow. One moment you see certain buttons in one area of the screen in another moment they move somewhere else.

I have been observing this on my laptop with 1600px screen width.

**Comment by tobias-klein** [comment]
@zhuiks Any suggestion on how to fix this?

**Comment by zhuiks** [comment]
The menu is a flex container with some sub-containers that are holding the buttons. We can:
1. Either put every button directly in the main container, then the size change would move just a few buttons and not the whole group.
2. Or make separate three menu rows: general, tags and selected verse. 
 
Later when after implementation of #346 we can move all tags buttons into tags sidebar. And maybe move selected verse buttons to be a popup over selected verse.

**Comment by tobias-klein** [comment]
Not relevant anymore due to the changes regarding the verse context menu.
