### ISSUE TITLE
Easily choose many tags at the same time

### ISSUE THREAD

**Issue by debritto** [ezra-bible-app/ezra-bible-app#528]
Hi guys! When I want to explore some tags verses, I need to choose tags one at a time, since the options menu doesn't allow multiple marking. 

![choose_tags](https://user-images.githubusercontent.com/9845780/142671861-1c049e51-70da-4cb3-bd8f-c5822806ffd3.png)

Is it possible to put a option to easily "mark all' tags? Or even allow the possibility to mark multiple tags at time?

Warm regards!

**Comment by tobias-klein** [comment]
The easy thing that could be done here is to keep the menu open until you confirm the selection with an OK button.

I'm not sure about an option to select all tags at once. I can see how it could make sense for a group of similar tags. But once you have a large collection of tags it's not so practical anymore for the whole list.

**Comment by debritto** [comment]
I think that an OK button is a very good idea. 
Besides this, if it's possible to have meta tags working ( #529 ) it will be a good idea to have a mark all tags from a meta tag at once option.

**Comment by tobias-klein** [comment]
This would be rather easy to implement.
@zhuiks Any thoughts?
