### ISSUE TITLE
Copy "Comparison Window" to Clipboard

### ISSUE THREAD

**Issue by debritto** [ezra-bible-app/ezra-bible-app#537]
Hi
Is it possible to copy the content of the comparisson window to Clipboard?

![image](https://user-images.githubusercontent.com/9845780/142952774-e3bf4f4a-fc0b-4891-b9ad-533ee34227a7.png)

It's a good option for those writing sermons or theological articles.
Warm regards

**Comment by tobias-klein** [comment]
Yes, we could look into that. I can see how this might be useful. Something more solid would be an actual file export (exporting to a word document). The clipboard may be a bit fragile when it comes to dealing with HTML. Do you think a file export would serve the purpose as well?

**Comment by debritto** [comment]
Yes. An exportation will solve the problem. I understand that are issues related to clipboard copy.
Thank you so much.
