### ISSUE TITLE
Bible book locale not rendered in case language code is hyphenated

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#539]
It seems that the Bible book locales are not loaded correctly when the respective locale code is hyphenated. Based on the files from the [locales.d](https://github.com/ezra-bible-app/node-sword-interface/tree/master/locales.d) folder my guess is that the root cause could be the separating character. Ezra Bible App uses the hyphen (-) for locales that have a country part. However, the files in locales.d use an underscore (_). 

The example below is when using the Brazilian Portuguese locale.

![image](https://user-images.githubusercontent.com/9845780/142950885-cc4ca27f-fb80-4816-8ae2-2a9e7e4b7442.png)

_Originally posted by @debritto in https://github.com/ezra-bible-app/ezra-bible-app/discussions/538_

**Comment by tobias-klein** [comment]
@debritto Planning to fix this in the next release!

**Comment by tobias-klein** [comment]
@debritto 
This is how it looks based on the fix!
![image](https://user-images.githubusercontent.com/17739895/143496733-dcfcb859-d5b2-44f1-9e0b-fa306e825921.png)

**Comment by debritto** [comment]
Woow! Awesome. Perfect! Thank you so much Brother!
