### ISSUE TITLE
Move New Tag button to tag list panel

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#572]
The New Tag button should be moved to the tag list panel, since this function is so closely related to that panel.

Prototype:

![image](https://user-images.githubusercontent.com/17739895/146680363-2aceffc3-3c82-401f-b709-811bfa2d07a2.png)

**Comment by tobias-klein** [comment]
@zhuiks @augustin-colesnic @debritto
This is a prototype. I put the "new tag button" just with the icon (no text) right next to the filter field on top of the tag panel.

Does this make sense from your perspective?

**Comment by debritto** [comment]
Hi @tobias-klein !
Yes, it makes sense. 
This strategy will guarantee a clean and sleek design of the application. 
Great idea!
