### ISSUE TITLE
Ubuntu 22.04  Ezra Bible App package request

### ISSUE THREAD

**Issue by reyespinosa1996** [ezra-bible-app/ezra-bible-app#684]
The new LTS release 22.04 of Ubuntu has been released, Ezra Bible App 1.6 have not yet include a specific release for this Ubuntu version. @tobias-klein could it be included for this release, or should we wait into the next 1.7?

**Comment by tobias-klein** [comment]
@reyespinosa1996 Did you test the existing 20.04 package on 22.04? Sometimes packages keep working on later releases. If the existing package doesn't work we can definitely add package generation for 22.04. This probably be for 1.7, though.

**Comment by reyespinosa1996** [comment]
I just try it in a VM and it doesn't work complaining about libicu66 missing in jammy repositories. The Debian 11 release complain about libicu67 also missing, the version available in Jammy is libicu70. So I will wait until Ezra Bible App 1.7 to upgrade my main system. For further releases it may be considered to have a minimum version required (libicu => 60 for example) in this way further releases of Debian and Ubuntu may be unified with a single release.

**Comment by tobias-klein** [comment]
Ok, thanks for checking. Let's plan this for 1.7!
