### ISSUE TITLE
Export tag in open format: odt or html

### ISSUE THREAD

**Issue by LAfricain** [ezra-bible-app/ezra-bible-app#8]
It would be nice to have the possibility to export in a open format, as odt or html. Currently it's just in docx.
I don't use Word or Windows, and I won't use it.

**Comment by LAfricain** [comment]
I don't know if it can be helpful, but [teus benschop](https://github.com/teusbenschop) may have ideas about that.

**Comment by tobias-klein** [comment]
I would prefer ODT as well, however at the time when I implemented the export I didn't find a decent JavaScript library for ODT/OpenDocument export. One thing, though. LibreOffice is perfectly fine opening docx and other [Microsoft Office OpenXML](https://en.wikipedia.org/wiki/Office_Open_XML) documents. I can have another look, but the implementation of this feature request largely depends on the availability of a fitting library that can be integrated with an Electron/JS application.

**Comment by LAfricain** [comment]
>LibreOffice is perfectly fine opening docx and other Microsoft Office OpenXML documents

Yes I know, it's much more to be coherent with the opensource spirit.
