### ISSUE TITLE
Fedora 33 & 35 builds broken

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#803]
Since a few days the Fedora 33 & 35 builds are broken on GitHub Actions.

The builds both fail when running the rpm packaging step.

**Comment by sammyj85** [comment]
Fedora 35 lasted only a month after this was raised until it was EOL.

Therefore Fedora 35 and earlier are now all end of life. Is there a reason why there are builds for these old versions?

On the other hand, I tried both the 35 and 37 packages on Fedora 36 (x86_64), and it fails. I have a libicu at version 69, but it wants a "libicu69", which doesn't exist.

https://src.fedoraproject.org/rpms/libicu69

It might be helpful creating a Fedora 36 release, which is still supported. Fedora releases only last a year and a month, which means the latest two versions are the ones which are supported (with a month of overlap of three versions).

**Comment by tobias-klein** [comment]
@sammyj85 
Good point!

Why are there builds for old versions? My assumption was that not everyone upgrades to the latest version all the time.

It may be valid to only support the latest Fedora.

We may get rid of the libicu dependency entirely (it is not needed on macOS or Android either) to make it easier with the packaging and compatibility.

Will look into this.

**Comment by sammyj85** [comment]
Thanks.

You're juggling a lot of platform compatibility!

**Comment by tobias-klein** [comment]
I created an issue to remove the libicu dependency on Linux, see #878.
