### ISSUE TITLE
Limit verse text column width

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#815]
For better readability the verse text column width should be limited. This is based on a suggestion from @magicsysrq, see #814.

> Some fundamental exploration of line length and readability was conducted by Emil Ruder, a mid-twentieth century Swiss graphic designer.
> 
> Ruder concluded that the optimal line length for body text is 50–60 characters per line, including spaces (“Typographie”, E. Ruder).
> 
> Other [sources](http://webtypography.net/2.1.2) suggest that up to 75 characters is acceptable.

see https://baymard.com/blog/line-length-readability

**Comment by tobias-klein** [comment]
This is an example based on 60 characters verse width.

![image](https://user-images.githubusercontent.com/17739895/202892958-58950048-c0f8-40ec-bd2d-c1bef3eced71.png)

@magicsysrq Any feedback?

**Comment by magicsysrq** [comment]
Yes, this is looking good. I've never heard of Emil Ruder. Thank you! I'm going to read up on him.
