### ISSUE TITLE
Release APK on Github

### ISSUE THREAD

**Issue by meichthys** [ezra-bible-app/ezra-bible-app#919]
It would be nice if the apk was released on Github so we could install it directly instead of having to use the play store. It would also allow apps like Obtainium to install it.

Probably relates to #229

**Comment by tobias-klein** [comment]
@meichthys Thanks for your suggestion. This could be done by simply uploading the APK file on GitHub. I could do that for future releases.

**Comment by sammyj85** [comment]
F-Droid is another open source app store alternative to the Play Store. Just as another suggestion for a place to put the APK.

https://f-droid.org/

**Comment by tobias-klein** [comment]
@meichthys The latest release apk has been uploaded on GitHub! I am therefore closing this issue!
See https://github.com/ezra-bible-app/ezra-bible-app/releases/tag/1.12.0

**Comment by alerque** [comment]
Distribution via F-Droid would be nice too, but that is a totally different beast than requested in this issue. Obtainium and others just round up and install existing resources (as in this issue being about just attaching an APK to the GH releases. That's all well and good, but the point of F-Droid is a provable open source toolchain that generates reproducible packaging. There are many clients for the F-Droid builds and also alternative build systems too. You don't just post APK/releases though, you post the sources and make sure the build toolchain is all worked out so the output is reproducible.
