### ISSUE TITLE
Add option that synchronizes the font size of the Bible text with the font size used in the side panel

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#921]
This is based on a request from @BeForgiven-Info, see discussion in #914.

**Comment by tobias-klein** [comment]
I'll have look once I start working on this! I hope to get something implemented for the next release.

**Comment by tobias-klein** [comment]
@BeForgiven-Info I just added a new option. This will become available as part of version 1.12.

**Comment by BeForgiven-Info** [comment]
Thank you!

Tom Sullivan
***@***.***
FAX: 815-301-2835
