### ISSUE TITLE
Debian 12 Ezra Bible App package is missing in /releases section. 

### ISSUE THREAD

**Issue by reyespinosa1996** [ezra-bible-app/ezra-bible-app#929]
Hello Team. The Debian 12 release took place a week ago. It would be great if we could have a specific package built against this version for the next Ezra release.

**Comment by tobias-klein** [comment]
Hi @reyespinosa1996 
Could you test the package for Debian 12?
Here is a download link to a snapshot: https://github.com/ezra-bible-app/ezra-bible-app/suites/17907167525/artifacts/1028601960

**Comment by tobias-klein** [comment]
@reyespinosa1996 Any feedback on the package for Debian 12?

**Comment by reyespinosa1996** [comment]
Sorry for the delay, unfortunately I'm no longer using Debian as my OS. Maybe someone else in the community can step ahead and test it.
