### ISSUE TITLE
Synchronisation with Dropbox fails on Android 13

### ISSUE THREAD

**Issue by lxs602** [ezra-bible-app/ezra-bible-app#934]
Hi, I have tried synchronising with Dropbox, but after clicking through the agreement pages, linking does not succeed. I am happy to provide bug reports (if told how).

Thanks, 

Luke

_Originally posted by @lxs602 in https://github.com/ezra-bible-app/ezra-bible-app/discussions/727#discussioncomment-6355108_

**Comment by tobias-klein** [comment]
Thanks for reporting this! Unfortunately, I do not have an Android 13 device and there is currently no good debugging approach for end users. I could try to reproduce this in the Android emulator with version 13.

**Comment by tobias-klein** [comment]
@lxs602 I just tried this in an Android 14 emulator and there the linking succeeded. So I could not reproduce this issue yet.
