### ISSUE TITLE
Wrong text direction for Hebrew Bibles

### ISSUE THREAD

**Issue by mttyhw** [ezra-bible-app/ezra-bible-app#938]
Noticed that the text direction is left to right for Hebrew.

**Comment by tobias-klein** [comment]
Yes, this is indeed a bug.

We would have to figure out how to handle the formatting of the HTML text in case of RTL text direction. And maybe this would also influence the layout overall in the Bible text area. Any feedback anyone?

**Comment by Llewellynvdm** [comment]
This is how we did that for [Psalm 18](https://getbible.net/codex/%D7%AA%D6%B0%D6%BC%D7%94%D6%B4%D7%9C%D6%B4%D6%BC%D7%99%D7%9D/118)

We simply used the HTML [RTL](https://git.vdm.dev/getBible/joomla-component/src/branch/master/site/views/app/tmpl/default_getbibletext.php#L43), and [LTR](https://git.vdm.dev/getBible/joomla-component/src/branch/master/site/views/app/tmpl/default_getbibletext.php#L43) to manage this directly on the page.

**Comment by Llewellynvdm** [comment]
But we also in the body add the [dir](https://git.vdm.dev/getBible/joomla-component/src/branch/master/site/views/app/view.html.php#L64) value now...

So the outcome is:
![image](https://github.com/ezra-bible-app/ezra-bible-app/assets/5607939/cb677c0a-eafb-4c79-b324-cc8016f2457d)

**Comment by tobias-klein** [comment]
Thank you @Llewellynvdm!
I'll have a look at those HTML options.
The text alone may be easy based on that.
Making adjustments for the overall layout in the Bible browser may be more effort.
We could start just with the text (if easily possible) and see whether the layout stuff could be a second step in the future.

**Comment by tobias-klein** [comment]
@mttyhw @Llewellynvdm 
I made some adjustments and it looks like this now for RTL text.

* Text is shown in RTL direction.
* Tags are right-aligned.

![image](https://github.com/ezra-bible-app/ezra-bible-app/assets/17739895/0a14599c-2d49-4da7-b574-e90f52ca0493)

Any feedback?
This will be released as part of 1.12.0 (a few weeks from now).

**Comment by mttyhw** [comment]
Looks good, I appreciate the work you all are doing.
