### ISSUE TITLE
Copy verses to clipboard including html formatting

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#962]
see discussion #952.

Retain the following formatting when copying verses to clipboard:
* transChange elements as italic text.
* Red letter words.
* Paragraphs/line breaks.
* Verse numbers as superscript.

**Comment by tobias-klein** [comment]
@Opv12
This turned out more complicated than I thought.

The source text from SWORD comes in a form that is not directly containing HTML elements for the formatting.

Example - Mark 2:18:

`<note n="A" osisID="Mark.2.18.xref.A" type="crossReference"><reference osisRef="Mark.2.18-Mark.2.22">Mark 2:18-22</reference>: <hi type="italic"><reference osisRef="Matt.9.14-Matt.9.17">Matt 9:14-17</reference>; <reference osisRef="Luke.5.33-Luke.5.38">Luke 5:33-38</reference></hi></note><w lemma="strong:G2491">John’s</w> <w lemma="strong:G3101">disciples</w> <w lemma="strong:G5330">and the Pharisees</w> <w lemma="strong:G3522">were fasting</w>; <transChange type="tenseChange"><w lemma="strong:G2064">and they came</w></transChange> <transChange type="tenseChange"><w lemma="strong:G3004">and said</w></transChange> <w lemma="strong:G1223 strong:G5101">to Him, “Why</w> <w lemma="strong:G2491">do John’s</w> <w lemma="strong:G3101">disciples</w> <w lemma="strong:G3101">and the disciples</w> <w lemma="strong:G5330">of the Pharisees</w> <w lemma="strong:G3522">fast</w>, <w lemma="strong:G3101">but Your disciples</w> <w lemma="strong:G3522">do not fast</w>?”`

What's done in Ezra Bible App in this case is to use CSS to format the respective elements correctly. However, when you copy this raw text to the clipboard and then paste the text somewhere else, the CSS is missing and therefore, the formatting is not transferred.

What we could do is to convert certain elements into basic html like `<i></i>` and `<font color=""></font>`.

The only formatting I can think of is:
* Italic text
* Red-letter words

Is there any other formatting you were thinking of?

We could try to convert the source elements to basic html elements and based on that achieve the transfer of the formatting.

**Comment by Opv12** [comment]
Thanks.  I can't think of any additional actual formatting that would be needed other than (1) the italics to distinguish the words added by the translators and (2) the words of Chrsit in red.  The only other thought that comes ot mind related to format really has nothing to do with the font (italic or red, etc) but rather with the the actual layout of the text when pasted, for example, various options for where the associated verse references could be placed, i.e., before or after a verse, before or after a block of verses, etc.  That could get rather complicated, I suppose, as it relates to copying and pasting all verses having the same tag, as those verses would likely be from a variety of different books, chapters, etc.  That's an aspect I hadn't really thought through.  Thanks again for your interest.
